#!bin/bash
wget https://raw.githubusercontent.com/Arioxss/bash-test/footest/grel.up
wget https://raw.githubusercontent.com/Arioxss/bash-test/footest/rtrlstrongswan
wget https://raw.githubusercontent.com/Arioxss/bash-test/footest/nftables
wget https://github.com/Arioxss/bash-test/blob/footest/demo.wsr
